apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: elyaash-dev
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
      version: "17.x.x"  
  interval: 1h
  values:
    architecture: standalone
    auth:
      enabled: true
      password: "${runtime.secretsManager.getSecret('redis-password')}"
    master:
      persistence:
        enabled: true
        size: 8Gi
    metrics:
      enabled: true
